-- CreateTable
CREATE TABLE "DeletedSolicitud" (
    "id" SERIAL NOT NULL,
    "originalId" INTEGER,
    "procesoId" INTEGER,
    "procesoSourceKey" TEXT,
    "externalId" TEXT,
    "codigoProceso" TEXT,
    "nombreProceso" TEXT,
    "entidad" TEXT,
    "objeto" TEXT,
    "fuente" TEXT,
    "aliasFuente" TEXT,
    "modalidad" TEXT,
    "perfil" TEXT,
    "departamento" TEXT,
    "estadoFuente" TEXT,
    "fechaPublicacion" TIMESTAMP(3),
    "fechaVencimiento" TIMESTAMP(3),
    "valor" DOUBLE PRECISION,
    "linkDetalle" TEXT,
    "linkSecop" TEXT,
    "linkSecopReg" TEXT,
    "estadoSolicitud" TEXT,
    "observacion" TEXT,
    "ciudad" TEXT,
    "sede" TEXT,
    "plataforma" TEXT,
    "fechaCierre" TIMESTAMP(3),
    "procStep" INTEGER NOT NULL DEFAULT 0,
    "procData" JSONB NOT NULL DEFAULT '{}',
    "obsData" JSONB NOT NULL DEFAULT '[]',
    "docData" JSONB NOT NULL DEFAULT '[]',
    "asignaciones" JSONB NOT NULL DEFAULT '[]',
    "revisor" TEXT,
    "aprobador" TEXT,
    "usuarioRegistro" TEXT,
    "emailRegistro" TEXT,
    "cargoRegistro" TEXT,
    "entidadRegistro" TEXT,
    "createdAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3),
    "deletedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedByUsuario" TEXT,
    "deletedByEmail" TEXT,

    CONSTRAINT "DeletedSolicitud_pkey" PRIMARY KEY ("id")
);
